### ISSUE TITLE
About distributed training

### ISSUE THREAD

**Issue by zjc19980405** [serend1p1ty/SeqNet#11]
Can you provide distributed training？

**Comment by serend1p1ty** [comment]
@zjc19980405  I'm sorry. I've actually tried to implement distributed training before. However, there are some problems with circle-queue / look-up-table synchronization among multiple GPUs in the OIM function. At present, I don't have multiple GPUs, so the code of distributed training can't be implemented temporarily.

**Comment by serend1p1ty** [comment]
I am also looking forward to a PR about this.

**Comment by zjc19980405** [comment]
ok, thanks.
