### ISSUE TITLE
CUHK-SYSU/annotations/Images.mat not found.

### ISSUE THREAD

**Issue by mustansarfiaz** [serend1p1ty/SeqNet#12]
Respected author,

I found your paper very interesting. I am trying to retrain the model using CUHK-SYSU dataset. 
I could not find the CUHK-SYSU/annotations/Images.mat file.

from where I can get this file?
however, PRW dataset is working fine.

Thanks in advance.

**Comment by serend1p1ty** [comment]
Hi, I am sorry to reply so late. You can find the file at https://drive.google.com/file/d/1z3LsFrJTUeEX3-XjSEJMOBrslxD2T5af/view
