### ISSUE TITLE
engine.py命名问题

### ISSUE THREAD

**Issue by XDWang97** [serend1p1ty/SeqNet#16]
你好👋，对这个engine.py的命名很敢兴趣，这个有什么讲究吗？里面是与训练相关的，一般不都是train.py吗

**Comment by serend1p1ty** [comment]
文件的命名和模块的组织主要参考的是：https://github.com/pytorch/vision/tree/main/references/detection
engine.py中一般包含train_one_epoch()这个函数，包含了用户自定义的一些训练逻辑。
还有evaluate相关的一些函数。

**Comment by XDWang97** [comment]
3q!
