### ISSUE TITLE
Code for the "NAE+  SeqNet" version for compare

### ISSUE THREAD

**Issue by Smalltarget108** [serend1p1ty/SeqNet#19]
I have tried your code, it is really concise and easy to understand.
In  order to learn it more comprehensively， 
May you  please also release the NAE+  SeqNet version for compare

Many thanks！

**Comment by serend1p1ty** [comment]
Sorry, I have not yet implement SeqNet on NAE+. Maybe you can have a try.

**Comment by Smalltarget108** [comment]
Thank you also
