### ISSUE TITLE
run python train.py can't get the search results

### ISSUE THREAD

**Issue by circlety** [serend1p1ty/SeqNet#20]
When I run **python train.py --cfg $ROOT/exp_cuhk/config.yaml --ckpt $ROOT/exp_cuhk/epoch_19.pth**, I can't get the search results in demo_imgs. So I want to ask if it should be **python demo.py --cfg cfg $ROOT/exp_cuhk/config.yaml --ckpt $ROOT/exp_cuhk/epoch_19.pth**. Thanks!

**Comment by serend1p1ty** [comment]
@circlety Yes, you should run demo.py, the error has been fixed in README.md

**Comment by circlety** [comment]
Thank you for your answer!
But for demo.py, it throws the error "**RuntimeError: Expected tensor for argument #1 'input' to have the same type as tensor for argument #2 'rois'; but type Variable[CUDAType] does not equal Variable[CUDAType]**"
Could you give  me some advice?

**Comment by serend1p1ty** [comment]
what version of pytorch & torchvision are you using?

**Comment by circlety** [comment]
pytorch==1.1.0
torchvision==0.3.0

**Comment by serend1p1ty** [comment]
update
torch==1.2.0
torchvision==0.4.0
As shown in requirements.txt

**Comment by circlety** [comment]
OK, I will try, thanks!
