### ISSUE TITLE
hi，your model in google can not find

### ISSUE THREAD

**Issue by mikeswf** [serend1p1ty/SeqNet#21]
https://drive.google.com/file/d/1wKhCHy7uTHx8zxNS62Y1236GNv5TzFzq/view?usp=sharing
https://drive.google.com/file/d/1I9OI6-sfVyop_aLDIWaYwd7Z4hD34hwZ/view?usp=sharing
this two we can not download for the reason that in google 回收站

**Comment by serend1p1ty** [comment]
sorry, fixed.
