### ISSUE TITLE
hi, have you tried train seqnet with both cuhk-sysu and prw?

### ISSUE THREAD

**Issue by caposerenity** [serend1p1ty/SeqNet#22]
Thank you for your strong codebase, I recently try to train seqnet with both cuhk-sysu and prw, but the results even get worse. I'm wondering whether the author have tried such a setting?

**Comment by serend1p1ty** [comment]
@caposerenity Sorry to reply so late. I haven't tried to train SeqNet with both these two datasets.
However, CUHK-SYSU and PRW have different data distribution, the latter is more difficult.
So I think the two datasets will have a negative impact on each other.
