### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by fu33** [serend1p1ty/SeqNet#23]
你好，为什么在使用prw数据集进行训练的时候，top-1指标怎么总是低4%左右？
可以分享一下prw数据集跟cuhk_sysu数据集的代码吗？

**Comment by serend1p1ty** [comment]
使用的是代码中提供的prw.yaml配置文件，并且没有做任何修改吗？
prw数据集跟cuhk_sysu数据集的代码指的是什么？

**Comment by fu33** [comment]
没有修改prw.yaml配置文件，但是我的机器没跑出来，但是每次跑出来的recall与ap值挺低的，我想是不是这个原因；能通过微调测试阶段的nms值来提高recall和ap的值吗？
我想参考一下你写的prw与cuhk_sysu数据集预处理的代码。
