### ISSUE TITLE
工程问题

### ISSUE THREAD

**Issue by Jiangsiping** [serend1p1ty/SeqNet#25]
作者您好，我最近在Nvidia NX上做一个行人检测+行人识别的项目，我采用yolov5+reid的方案，但是跟踪速度不能满足我的需求，我想用这个算法来替换我的方案。因此我想请教三个问题，1:如果我减小这个网络，将速度提升至实时，是否会对精度有特别大的影响。2:这个算法能否应用于同时对三个行人识别的场景。3:我是否可以理解为，person search可以完全替代且优于检测+reid的方案。4:希望您能提供一点思路和建议。
最后，祝您生活愉快

**Comment by serend1p1ty** [comment]
1. 没做过相关实验，但感觉减小网络不会降低太多精度。可以尝试将resnet50替换成resnet34，或者将c4-faster-rnn替换成fpn-faster-rcnn。
2. 可以应用。提取出三个行人的特征，然后对每张图片里的行人embedding点积求相似度就行了。
3. person search任务的初衷就是为了替代检测+reid。

**Comment by serend1p1ty** [comment]
> 作者您好，我最近在Nvidia NX上做一个行人检测+行人识别的项目，我采用yolov5+reid的方案，但是跟踪速度不能满足我的需求，我想用这个算法来替换我的方案。因此我想请教三个问题，1:如果我减小这个网络，将速度提升至实时，是否会对精度有特别大的影响。2:这个算法能否应用于同时对三个行人识别的场景。3:我是否可以理解为，person search可以完全替代且优于检测+reid的方案。4:希望您能提供一点思路和建议。 最后，祝您生活愉快

1. 没做过很多相关实验，直觉上轻微地减小网络不会降低太多精度。可以尝试将resnet50替换成resnet34，或者将c4-faster-rnn替换成fpn-faster-rcnn。我记得之前换成fpn会掉一个点左右，时间太久，具体数字记不清了。
2. 可以应用。提取出三个行人的特征，然后对每张图片里的行人embedding点积求相似度就行了。
3. person search任务的初衷就是为了替代检测+reid，建议直接使用person search模型。

**Comment by Jiangsiping** [comment]
感谢！
