### ISSUE TITLE
The PRW dataset could not be downloaded

### ISSUE THREAD

**Issue by oyh374073360** [serend1p1ty/SeqNet#27]
Dear Doctor Li,

I do not have permission to download the PRW dataset.  Could you please give me a link to download it.

Best Regards,

graduate student

**Comment by serend1p1ty** [comment]
Try to download it from this [baiduyun](https://pan.baidu.com/s/1U5YaSHuT6Cgl6xnjzh11Ow?pwd=q3q9) link.

BTW, I am a master, not a doctor.

**Comment by oyh374073360** [comment]
Thank you very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "serend1p1ty/SeqNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月3日(星期天) 凌晨3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [serend1p1ty/SeqNet] The PRW dataset could not be downloaded (Issue #27)





 
Try to download it from this baiduyun link.
