### ISSUE TITLE
Add video for testing

### ISSUE THREAD

**Issue by ThanhPham1987** [serend1p1ty/SeqNet#3]
Hi @serend1p1ty ,
How to read video file  into  your source code?
Best regards,
PeterPham

**Comment by serend1p1ty** [comment]
Currently, the data is loaded from PyTorch Dataloader in test phase.

https://github.com/serend1p1ty/SeqNet/blob/a1c3da3b5450a43ad5f859a473870c767e685f3d/engine.py#L91

You can modify it so that reading from video.

**Comment by A7777-gp** [comment]
Thank you for your work. Could you please tell me how to change the input into the camera

**Comment by serend1p1ty** [comment]
@A7777-gp 
Video testing depends on single image testing #4.
You can refer to:
- https://github.com/serend1p1ty/person_search/blob/master/tools/demo.py
- https://github.com/serend1p1ty/person_search/blob/5116fc6bab20f1adb2d3d959343abaa400b0735e/lib/models/network.py#L161

**Comment by serend1p1ty** [comment]
@A7777-gp Single image demo has been implemented. Please refer to [demo.py](https://github.com/serend1p1ty/SeqNet/blob/master/demo.py)
