### ISSUE TITLE
Default configuration for the provided checkpoint?

### ISSUE THREAD

**Issue by Wuzimeng** [serend1p1ty/SeqNet#32]
Hi, I downloaded the checkpoint file you provided in README and tried to train one more epoch to observe something interesting. However, it raised error indicating that `loaded state dict has a different number of parameter groups` when calling `optimizer.load_state_dict(ckpt["optimizer"])`. I wonder whether there is some difference between the code here and that you used to generate [model](https://drive.google.com/file/d/1wKhCHy7uTHx8zxNS62Y1236GNv5TzFzq/view?usp=sharing) ?

**Comment by serend1p1ty** [comment]
You can check which parameters have been changed according to `ckpt["optimizer"]`. Maybe there is some small difference because I refactor code before. However, it doesn't matter. The current codebase can reproduce the performance mentioned in the paper.

**Comment by Wuzimeng** [comment]
Thanks, I checked `ckpt["optimizer"]` and found only some difference in presentation format. Therefore I wonder what `pytorch version` and `torchvision version` you used. (Meanwhile, I guess it was the version that caused my failure to align the performance mentioned in your paper.)

**Comment by serend1p1ty** [comment]
As shown in requirements.txt, I used torch==1.2.0

**Comment by Wuzimeng** [comment]
Thanks, finally I made it. After changing the version, I got the desired result.
