### ISSUE TITLE
Loss is nan when training cuhk_sysu dataset

### ISSUE THREAD

**Issue by ShaohuaDong2021** [serend1p1ty/SeqNet#34]
Thanks for your amazing paper!

But when I train this model on cuhk_sysu dataset (" python train.py --cfg configs/cuhk_sysu.yaml"), loss is nan in the second epoch.

![1689962710569](https://github.com/serend1p1ty/SeqNet/assets/95509960/a8f896b8-5361-4427-b7f7-abc0d6e65526)

Do you have any ideas to solve this problem? 
Thanks a lot!

**Comment by serend1p1ty** [comment]
@ShaohuaDong2021 Hi, you can refer to https://github.com/serend1p1ty/SeqNet/issues/26

**Comment by serend1p1ty** [comment]
If your problem is still not resolved, feel free to reopen this issue.
