### ISSUE TITLE
About demo.py .

### ISSUE THREAD

**Issue by Yx1322441675** [serend1p1ty/SeqNet#4]
Do you have demo.py or visualize.py?If you have,Can you share it?

**Comment by serend1p1ty** [comment]
You can refer to https://github.com/serend1p1ty/person_search/blob/master/tools/demo.py
I will implement one when free.

**Comment by serend1p1ty** [comment]
Single image demo has been implemented. Please refer to [demo.py](https://github.com/serend1p1ty/SeqNet/blob/master/demo.py)
